### PR TITLE
Extend calculation methods to handle int indexes instead of days

### PR DESCRIPTION
**Pull request by benHeid**
Please review especially the overwritten functions.. Is there are prettier way of doing that?

### CODE REVIEW

**Comment by timueh** [comment]
I refactored a bit in the spirit of *don't repeat yourself*, e.g.:

```julia
function get_weights(R::Real, past::Day, future::Day, k_gen::Day)
    [ R^(7 / Dates.value(k_gen)) * ones(Dates.value(past)); ones(1 + Dates.value(future)) ]
end

get_weights(R::Real, past::Int, future::Int, k_gen::Int) = get_weights(R, Day(past), Day(future), Day(k_gen))
```

Two things:

1. The notebook is no longer working, because when reading the CSV values we need to make sure we convert the `days` column to a `Vector{Dates}`. I added a note in the respective cell.
2. ~~Perhaps we should drop all keywords. At the moment, there is no consistency between using the keywords `past`, `future`, `present`. Can you fix that at some point?~~ Fixed this in the code, but did not check the notebook. [`main.jl`](example/main.jl) runs flawlessly, see 54d8c54

**Comment by benHeid** [comment]
Thanks for your help. I updated the notebook and some code. However, two assert in compute acausal does not work well with my code. Since df_cases.days is an Array{Day} instead of Vector{Day}

**Comment by timueh** [comment]
An `Array{Day, 1}` is the same as `Vector{Day}`:
```julia
julia> using Dates

julia> v = Array{Day, 1}()
0-element Array{Day,1}

julia> typeof(v) == Vector{Day}
true
```
Perhaps, you have a row vector, i.e. `Array{Day, 2}`? Then, use `vec()`:

```julia
julia> w = [Day(2) Day(3)]
1×2 Array{Day,2}:
 2 days  3 days

julia> vec(w)
2-element Array{Day,1}:
 2 days
 3 days
```

**Comment by benHeid** [comment]
> 
> 
> An `Array{Day, 1}` is the same as `Vector{Day}`:
> 
> ```julia
> julia> using Dates
> 
> julia> v = Array{Day, 1}()
> 0-element Array{Day,1}
> 
> julia> typeof(v) == Vector{Day}
> true
> ```
> 
> Perhaps, you have a row vector, i.e. `Array{Day, 2}`? Then, use `vec()`:
> 
> ```julia
> julia> w = [Day(2) Day(3)]
> 1×2 Array{Day,2}:
>  2 days  3 days
> 
> julia> vec(w)
> 2-element Array{Day,1}:
>  2 days
>  3 days
> ```

The problem was that I used DateTime instead of Date.

**Comment by timueh** [comment]
all working? can I close the PR?

**Pull request merged**
